let countries = ["Afghanistan","Albania","Algeria","Andorra","Angola","Antigua and Barbuda","Argentina","Armenia","Australia","Austria","Azerbaijan","The Bahamas","Bahrain","Bangladesh","Barbados","Belarus","Belgium","Belize","Benin","Bhutan","Bolivia","Bosnia and Herzegovina","Botswana","Brazil","Brunei","Bulgaria","Burkina Faso","Burundi","Cambodia","Cameroon","Canada","Cape Verde","The Central African Republic","Chad","Chile","The People's Republic of China","Colombia","The Comoros","The Democratic Republic of the Congo","The Republic of the Congo","Costa Rica","Croatia","Cuba","Cyprus","The Czech Republic","Denmark","Djibouti","Dominica","The Dominican Republic","East Timor","Ecuador","Egypt","El Salvador","Equatorial Guinea","Eritrea","Estonia","Eswatini","Ethiopia","Fiji","Finland","France","Gabon","The Gambia","Georgia","Germany","Ghana","Greece","Grenada","Guatemala","Guinea","Guinea-Bissau","Guyana","Haiti","Honduras","Hungary","Iceland","India","Indonesia","Iran","Iraq","Ireland","Israel","Italy","Cote d'Ivoire","Jamaica","Japan","Jordan","Kazakhstan","Kenya","Kiribati","North Korea","South Korea","Kuwait","Kyrgyzstan","Laos","Latvia","Lebanon","Lesotho","Liberia","Libya","Liechtenstein","Lithuania","Luxembourg","Madagascar","Malawi","Malaysia","Maldives","Mali","Malta","The Marshall Islands","Mauritania","Mauritius","Mexico","The Federated States of Micronesia","Moldova","Monaco","Mongolia","Montenegro","Morocco","Mozambique","Myanmar","Namibia","Nauru","Nepal","The Netherlands","New Zealand","Nicaragua","Niger","Nigeria","North Macedonia","Norway","Oman","Pakistan","Palau","Palestine","Panama","Papua New Guinea","Paraguay","Peru","The Philippines","Poland","Portugal","Qatar","Romania","Russia","Rwanda","Saint Kitts and Nevis","Saint Lucia","Saint Vincent and The Grenadines","Samoa","San Marino","Sao Tome and Principe","Saudi Arabia","Senegal","Serbia","Seychelles","Sierra Leone","Singapore","Slovakia","Slovenia","The Solomon Islands","Somalia","South Africa","South Sudan","Spain","Sri Lanka","Sudan","Suriname","Sweden","Switzerland","Syria","Tajikistan","Tanzania","Thailand","Togo","Tonga","Trinidad and Tobago","Tunisia","Turkey","Turkmenistan","Tuvalu","Uganda","Ukraine","The United Arab Emirates","The United Kingdom","The United States","Uruguay","Uzbekistan","Vanuatu","The Vatican City","Venezuela","Vietnam","Yemen","Zambia","Zimbabwe","The Republic of Abkhazia","Artsakh","The Republic of China","The Cook Islands","Kosovo","Niue","The Turkish Republic of Northern Cyprus","The Sahrawi Arab Democratic Republic","Somaliland","South Ossetia","Transnistria"];
let new_countries =
    [
        "Prirwan",
        "Rerkeycao",
        "Bialize Harymal",
        "Rdanriimo",
        "Keelingi",
        "Nguilden",
        "Saintand Mie",
        "Igerran",
        "Tadad Bourgki",
        "North Crore",
        "Mistatesniasai",
        "Lena Tarre",
        "Gestan Island",
        "Canmorpu",
        "Slandsdangia",
        "Slandi Ngali",
        "South Ntecannti",
        "Gacu Kingdom",
        "Vietdormanlau Land",
        "Zberia",
        "Stanpornga",
        "Amon",
        "Ntarcti",
        "Coguaynor",
        "Viacroa Linin",
        "Stocos Rianesaint",
        "Andebe",
        "Eastern Tiana Mymitar",
        "Ganblic",
        "Western Waydachad",
        "Slandsldori",
        "Neaverde",
        "Kire",
        "Tacanizim",
        "Sica Neale",
        "Turunri",
        "Saintri Gorki",
        "Stanbia Guitou",
        "Diaba Bercam",
        "Ingua Diare",
        "Reudom Kiabisfgha",
        "Frenchlau",
        "Guaguam",
        "Wepa",
        "Landblic",
        "Nauri Golandu",
        "Ambrosia",
        "Angria",
        "Archenland",
        "Atlantis",
        "Avalon",
        "Averna",
        "Buranda",
        "Qumranistan",
        "Carbombya",
        "Costaguana",
        "Drenai Empire",
        "Elbonia",
        "Erewhon",
        "Herzoslovakia",
        "Latveria",
        "Laurania",
        "Molvania",
        "Paflagonia",
        "Pimlico",
        "Qumar",
        "Equatorial Kundu",
        "Ruritania",
        "San Serriffe",
        "‏Syldavia",
        "Borduria",
        "Tazbekistan",
        "Themyscira",
        "Uqbar",
        "‏Vulgaria",
        "Zembla"
    ];

if (module) module.exports = {
    countries: new_countries,
    resolutions: [
        "Support a Polar Bioconservation Expedition",
        "Declare the Northen Regions as an international pristine territory",
        "Commitment to global mass reforestation project",
        "Commit to an international space junk cleanup strategy",
        "Declare collective ownership of all Martian resources",
        "Refurbish Southern Hemisphere Long Range Space equipment",

        "Provide funding for international ocean cleanup initiative",
        "Information sharing for carbon capture technology",
        "Collective investment in international thorium development",
        "Information sharing initative in fusion energy development",
        "Reinstate international free trade agreements",
        "Establishment of stock market for global climate initatives",

        "International subsidy for high volume freight resumption",
        "Double World Health Organisation funding",
        "Reinforce international infectious reporting standards",
        "Redraft international WMD treaties to include cyber warfare",
        "Advocate for ban on space-based weapons systems",
        "Fund an international General AI safety commission",

        "Declare an international mental health crisis",
        "Redraw international biochemical safety standards plans",
        "Deploy foreign aid programs in the Desolate Zone",
        "Send aid to Zubrovka post 2020 crisis",
        "Draft island nation rehabilitation plans",
        "Commission for GDP economic target alternatives",

        "Redraft the Sustainable Development Goals",
        "Create an international educational standard",
        "Control measures against international organized crime",
        "Disclosure and investment into desalination technologies",
        "Improve post-secondary academic research incentives",
        "Standardisation of recognised engineering qualifications",

        "Foreign aid and massive infrastructure loan regulation",
        "Establishment of permanent Human Cultural Archive",
        "Open source international hydrogeological data"

    ]
};
